# Generated by Django 4.1.7 on 2023-03-06 16:59

from django.db import migrations, models

# db에 product라는 데이터를 어떻게 다룰건지 설정해줌
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
            ],
        ),
    ]
